#!/bin/sh

# Displays the following text banner generated with 'figlet -c -w 38 "delphin"'. The output of this command was first 
# pasted below and then any backquote (anywhere) and backslash (located at the end of a line) was escaped with slashes.
echo "       _      _       _     _
    __| | ___| |_ __ | |__ (_)_ __
   / _\` |/ _ \ | '_ \| '_ \| | '_ \\
  | (_| |  __/ | |_) | | | | | | | |
   \__,_|\___|_| .__/|_| |_|_|_| |_|
               |_|"